apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: webserver # Il faut que ça matche avec le label du Deployment !
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080 # K3s ouvrira ce port sur la machine Azure
